### ISSUE TITLE
Restrict file input to .c files only

### ISSUE THREAD

**Issue by Pipluppp** [Pipluppp/interpreter#10]
The scanner should not accept any other files and only read from `.c` files

**Comment by PaullyMac** [comment]
Want ba ni Ma'am here yung file name na 'di siya hardcoded right? As in parang pwede kang pumili ng file na want mong i-test as long as it is of one unique file type. If that so, then siguro we can use `scanf`() function.

Also, I think ang want ata ni Ma'am is of a different file extension (as in we can have a file extension of `.core`) which is named after our designed programming language. Amirite?

![image](https://github.com/user-attachments/assets/66b9abd1-6473-4519-b7e5-778078e9340e)

Thanks.

**Comment by Pipluppp** [comment]
https://github.com/Pipluppp/interpreter/commit/ae06d27f43af9209684be0b8f9e08dfdffcedf8a
